on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy to firebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@master
      with:
        node-version: '18.x'
    - run: npm install
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OWEN_TIMER }}"
        channelId: live
      env:
        FIREBASE_CLI_EXPERIMENTS: webframeworks
